

EXPECTED_RCS_MESSAGE_HEADERS = [
    "ID",
    "Contact Number",
    "Department",
    "User",
    "Status",
    "Direction",
    "Message Type",
    "Source",
    "Sub-Source",
    "Message Content",
    "Submitted At",
    "Delivered At",
    "Read At",
    "Failed At",
    "Failure Reason",
    "Corelation Id",
    "Created At",
    "Assistant ID",
    "Agent Name",
    "Agent Status",
    "Agent Sender Name",
    "Campaign Name",
]
