

active_environment: dev

environments:
  staging:
    base_url: "https://testqa.cpaas.globeteleservices.com"
    sms_send_path: "/api/sms/send"
    campaign_send_path: "/api/sms/campaign/send"
    template_send_path: "/api/sms/template/send"
    send_msg_path: "/api/sms/send-msg"
    sms_json_path: "/api/sms/json"
    webengage_send_path: "/api/v1/sms/webengage/send"

    dlr_base_url: "http://140.245.230.67:8080"
    dlr_path: "/api/v1/dlr"

    dlr_verify_path: "/api/v1/dlr/verify"

    auth_token: ""
    campaign_id: "08284c94-ec11-4135-8f03-93b428b31669"
    template_id: "828"
    timeout_seconds: 15
    verify_ssl: true

  dev:
    base_url: "https://testqa.gtsstaging.com"
    sms_send_path: "/api/sms/send"
    campaign_send_path: "/api/sms/campaign/send"
    template_send_path: "/api/sms/template/send"
    send_msg_path: "/api/sms/send-msg"
    sms_json_path: "/api/sms/json"
    webengage_send_path: "/api/v1/sms/webengage/send"
    dlr_base_url: "http://140.245.230.67:8080"
    dlr_path: "/api/v1/dlr"
    dlr_verify_path: "/api/v1/dlr/verify"

    auth_token: ""
    campaign_id: "3e087f65-bf67-42ef-95c7-c37d5c28866f"
    template_id: "55515"
    timeout_seconds: 15
    verify_ssl: true

  production:
    base_url: "https://test.cerfsolutions.com"
    sms_send_path: "/api/sms/send"
    campaign_send_path: "/api/sms/campaign/send"
    template_send_path: "/api/sms/template/send"
    send_msg_path: "/api/sms/send-msg"
    sms_json_path: "/api/sms/json"
    webengage_send_path: "/api/v1/sms/webengage/send"
    dlr_base_url: "http://140.245.230.67:8080"
    dlr_path: "/api/v1/dlr"
    dlr_verify_path: "/api/v1/dlr/verify"

    auth_token: ""
    campaign_id: "22709452-14e3-4896-b8a3-20341a22c2a8"
    template_id: "6513"  # TODO: Set the production template ID
    timeout_seconds: 15
    verify_ssl: true

  malaysia:
    base_url: "https://demo.mycpaasplus.com"
    sms_send_path: "/api/sms/send"
    campaign_send_path: "/api/sms/campaign/send"
    template_send_path: "/api/sms/template/send"
    send_msg_path: "/api/sms/send-msg"
    sms_json_path: "/api/sms/json"
    webengage_send_path: "/api/v1/sms/webengage/send"
    dlr_base_url: "http://140.245.230.67:8080"
    dlr_path: "/api/v1/dlr"
    dlr_verify_path: "/api/v1/dlr/verify"

    auth_token: ""
    campaign_id: "13288824-ef19-4385-8a25-4aef57d5c077"
    template_id: "39"
    timeout_seconds: 30
    verify_ssl: true
