

EXPECTED_RCS_CAMPAIGN_HEADERS = [
    "ID",
    "Campaign Name",
    "Type",
    "Department",
    "User",
    "Template",
    "Agent",
    "Status",
    "Total Messages",
    "Sent Count",
    "Delivered Count",
    "Read Count",
    "Interactions",
    "Failed Count",
    "Created At",
    "Scheduled At",
    "Send Type",
    "Started At",
    "Completed At",
    "Message Content",
    "Updated At",
]
